### PR TITLE
Visual 2A03 Remix

### PR DESCRIPTION
**Pull request by binji**
Based on http://www.qmtpro.com/~nes/chipimages/visual2a03/

### CODE REVIEW

**Comment by binji** [comment]
Not sure if you'd want this upstream, but I was pretty happy to see it working so well!

**Comment by floooh** [comment]
Wow nice :) I'll have a closer look some time next week, but it looks the changes don't add too much 'longterm maintenance overhead', so I'll be happy to merge the PR (besides, I want to make adding new CPUs easier anyway, so maybe the PR gives me some ideas where things could be better separated, if you have any thoughts on that, let me know :)

**Comment by floooh** [comment]
Well it's working nicely here, what a monster of a chip :)

I need to figure out a nicer visualization, I've grown a bit tired of the black background and desatured colors, and this chip with its fine detail drives the point home even more.

Screenshot 2023-01-08 at 10 56 39

**Comment by binji** [comment]
> so maybe the PR gives me some ideas where things could be better separated, if you have any thoughts on that, let me know

It was pretty painless for the most part, though it felt like I had to repeat myself a few times for reading nodes in perfect2a03, sim.c and trace.c. I can see the value in having an abstraction layer there, but since there are a lot of signals I wanted to view it ended up being a bunch of extra work.

**Comment by floooh** [comment]
FYI, I there's a missing ImGui::EndTabItem() at the end of ui_audio_status_panel(), I'm fixing this in my VIP branch (also a little tab-width confusion in the same function).

**Comment by floooh** [comment]
Ok, I also checked on Windows and Linux (no issues), and merged.

Next I'll add a GH Action script to test compilation (long overdue), will tinker a bit with a new color palette, and then upload a WASM version.

Many thanks again :)

**Comment by floooh** [comment]
Ok, it's live: https://floooh.github.io/visual2a03remix/

I tinkered a bit with the color palette, don't be surprised ;)

**Pull request merged**
